#!/usr/bin/env python3
# =========================================================================== #


def main():
    from grpc_tools import protoc

    protoPath        = './proto'
    pyGenFilesPath   = './build/gen'
    grpcGenFilesPath = './build/gen'
    mainProtoFile    = 'msg.proto'

    protoc.main((
        '',
        f'--proto_path{protoPath}',
        f'--python_out={pyGenFilesPath}',
        f'--grpc_python_out={grpcGenFilesPath}',
        f'{protoPath}/{mainProtoFile}',
    ))


if __name__ == '__main__':
    main()


# =========================================================================== #