"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

# ------------------------------------------------------------------------- //

# Server error codes
class ErrNo(_ErrNo, metaclass=_ErrNoEnumTypeWrapper):
    pass
class _ErrNo:
    V = typing.NewType('V', builtins.int)
class _ErrNoEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrNo.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    OK = ErrNo.V(0)
    KEY_NOT_FOUND = ErrNo.V(1)
    KEY_ALREADY_PRESENT = ErrNo.V(2)
    EXT_NOT_FOUND = ErrNo.V(3)
    SERVER_SHUTDOWN = ErrNo.V(7)

OK = ErrNo.V(0)
KEY_NOT_FOUND = ErrNo.V(1)
KEY_ALREADY_PRESENT = ErrNo.V(2)
EXT_NOT_FOUND = ErrNo.V(3)
SERVER_SHUTDOWN = ErrNo.V(7)
global___ErrNo = ErrNo


class Val(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATA_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    data: builtins.int = ...
    desc: typing.Text = ...
    def __init__(self,
        *,
        data : builtins.int = ...,
        desc : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"data",b"data",u"desc",b"desc"]) -> None: ...
global___Val = Val

class InsertReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    key: builtins.int = ...
    @property
    def val(self) -> global___Val: ...
    def __init__(self,
        *,
        key : builtins.int = ...,
        val : typing.Optional[global___Val] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"val",b"val"]) -> None: ...
global___InsertReq = InsertReq

class InsertAns(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERRNO_FIELD_NUMBER: builtins.int
    # note: default is 0 (OK) when unspecified
    errNo: global___ErrNo.V = ...
    def __init__(self,
        *,
        errNo : global___ErrNo.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"errNo",b"errNo"]) -> None: ...
global___InsertAns = InsertAns

class QueryReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    key: builtins.int = ...
    def __init__(self,
        *,
        key : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key"]) -> None: ...
global___QueryReq = QueryReq

class QueryAns(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERRNO_FIELD_NUMBER: builtins.int
    VAL_FIELD_NUMBER: builtins.int
    # note: default is 0 (OK) when unspecified
    errNo: global___ErrNo.V = ...
    @property
    def val(self) -> global___Val: ...
    def __init__(self,
        *,
        errNo : global___ErrNo.V = ...,
        val : typing.Optional[global___Val] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"val",b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"errNo",b"errNo",u"val",b"val"]) -> None: ...
global___QueryAns = QueryAns

# Used by the forwarding server (svc_comp)
class QueryAllAns(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERRNO_FIELD_NUMBER: builtins.int
    SIGA_FIELD_NUMBER: builtins.int
    MATR_FIELD_NUMBER: builtins.int
    # note: default is 0 (OK) when unspecified
    errNo: global___ErrNo.V = ...
    @property
    def siga(self) -> global___Val: ...
    @property
    def matr(self) -> global___Val: ...
    def __init__(self,
        *,
        errNo : global___ErrNo.V = ...,
        siga : typing.Optional[global___Val] = ...,
        matr : typing.Optional[global___Val] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matr",b"matr",u"siga",b"siga"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"errNo",b"errNo",u"matr",b"matr",u"siga",b"siga"]) -> None: ...
global___QueryAllAns = QueryAllAns

class ShutdownReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ShutdownReq = ShutdownReq

class ShutdownAns(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.bool = ...
    def __init__(self,
        *,
        status : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___ShutdownAns = ShutdownAns
